# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
