# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171222_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='anonymous', max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='评论内容...', max_length=1024, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, help_text='options', null=True),
        ),
    ]
