# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171222_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(help_text='options', null=True, verbose_name='引文地址'),
        ),
    ]
